# Generated by Django 4.1.3 on 2023-01-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datetime', models.DateTimeField()),
                ('caseNumber', models.CharField(default='', max_length=15)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('datetime', 'caseNumber', 'description', 'location', 'latitude', 'longitude')},
            },
        ),
    ]
