# Generated by Django 4.1.3 on 2022-12-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_incident_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
