# Generated by Django 4.1.3 on 2022-12-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_incident_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incident',
            unique_together={('datetime', 'caseNumber', 'description', 'location')},
        ),
    ]
